name: COREWIND Morro Bay Tow To Port
library: library
weather: central_ca.csv
service_equipment:
  - ctv1.yaml
  - ctv2.yaml
  - ctv3.yaml
  - ctv4.yaml
  - ctv5.yaml
  - ctv6.yaml
  - ctv7.yaml
  - cab.yaml  # Alternative to SOV w/ROV
  - dsv.yaml  # Alternative to SOV w/ROV
  - ahv.yaml
layout: morro_bay_9D_layout_ttp.csv
port_distance: 60  # 20/100 for West of Barra Island; 10 for Gran Canaria Island
inflation_rate: 0
workday_start: 6
workday_end: 22
start_year: 2002
end_year: 2021
project_capacity: 1200
port: morro_bay_port.yaml
# NOTE: No labor cost data is available in the assumptions
