repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
        - id: isort
          name: isort
          stages: [commit]

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
        - id: black
          name: black
          stages: [commit]
          language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        entry: mypy --install-types --non-interactive
        exclude: (^docs/|^tests/)

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]

-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
        exclude: ^tests/

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        exclude: (^tests/|^docs/)

# -   repo: local
#     hooks:
#     - id: pytest
#       name: pytest
#       stages: [commit]
#       entry: pytest --tb=line --deselect=setup.py tests/
#       language: system
#       types: [python]

#     - id: pytest-cov
#       name: pytest-cov
#       stages: [commit]
#       language: system
#       entry: pytest --cov=wombat --tb=no --ignore=*setup.py --cov-fail-under=80
#       types: [python]
#       pass_filenames: false
