default_language_version:
    python: python3
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
        - id: isort
          name: isort
          stages: [commit]

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    name: black
    stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.7.0'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    entry: mypy --install-types --non-interactive --config-file .mypy.ini
    exclude: (^docs/|^tests/)
    additional_dependencies: ["types-python-dateutil", "types-attrs", "types-PyYAML"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-executables-have-shebangs
  -   id: check-json
  -   id: check-yaml
      exclude: (^library/code_comparison/iea26/results/)|(^library/code_comparison/dinwoodie/results/)
  -   id: check-merge-conflict
  -   id: check-symlinks
  -   id: mixed-line-ending
  -   id: pretty-format-json
      args: [--autofix]


- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.5
  hooks:
  - id: ruff
    args: [--fix]

# -   repo: local
#     hooks:
#     - id: pytest
#       name: pytest
#       stages: [commit]
#       entry: pytest --tb=line --deselect=setup.py tests/
#       language: system
#       types: [python]

#     - id: pytest-cov
#       name: pytest-cov
#       stages: [commit]
#       language: system
#       entry: pytest --cov=wombat --tb=no --ignore=*setup.py --cov-fail-under=80
#       types: [python]
#       pass_filenames: false
