name: OSW_2019baseline
library: OSW_2019baseline
weather: vineyard_wind_weather_1998_2017.csv
service_equipment: [ctv1.yaml, ctv2.yaml, fsv.yaml, hlv.yaml, jackup.yaml, cable_vessel.yaml]
layout: layout.csv
inflation_rate: 0
fixed_costs: SAM_Singleowner_defaults.yaml
workday_start: 7
workday_end: 19
start_year: 1998
end_year: 2017
project_capacity: 1002
