operations_management_administration: 30.4  # all non-labor fixed costs
insurance: 0
annual_leases_fees: 0
operating_facilities: 0
environmental_health_safety_monitoring: 0
onshore_electrical_maintenance: 0
labor: 7.5
