name: dinwoodie_base_tow_to_port
library: DINWOODIE
weather: alpha_ventus_weather_2002_2014.csv
service_equipment: [ctv1.yaml, ctv2.yaml, ctv3.yaml]
layout: layout_tow_to_port.csv
port: base_port.yaml
inflation_rate: 0
fixed_costs: fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2003
end_year: 2012
project_capacity: 240
