name: port_testing
library: DINWOODIE
weather: alpha_ventus_weather_2002_2014.csv
service_equipment: [ctv1.yaml, hlv_requests.yaml]
layout: layout_port_test.csv
inflation_rate: 0
fixed_costs: fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2003
end_year: 2012
project_capacity: 240
site_distance: 0
port: base_port.yaml
