name: Broadshore Layout 1 - Tow-to-Port - Increase Failure Rates
start_year: 2000
end_year: 2019
service_equipment:
  - [ctv.yaml, 3]
  - cab.yaml
  - ahv.yaml
  - rov.yaml
layout: broadshore_layout_1_tow_increase_failure.csv
workday_start: 7
workday_end: 19
project_capacity: 600  # 15MW x 40 turbines
port: port_base.yaml
port_distance: 45.79
weather: ore_validation_58.0_-1.5.pqt
inflation_rate: 0
fixed_costs: fixed_costs.yaml
