name: Documentation

on:
  push:
    branches: [main]

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[docs]"

      - name: Build documentation
        run: |
          jupyter-book build docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
